platform :ios,'5.1.1'
pod 'ReactiveCocoa'
pod 'Routable'
pod 'AFNetworking', '~> 1.0'
pod 'DCKeyValueObjectMapping'
pod 'CocoaLumberjack'
pod 'TMCache'
pod 'MagicalRecord'
pod 'Reachability'
pod 'Base64nl'
pod 'NUI'
pod 'JSONModel'
pod 'Mantle'
pod 'Lockbox'
pod 'FCFileManager'
pod 'StandardPaths'
pod 'UI7Kit'
pod 'SDWebImage'
pod 'Appirater'
pod 'HMSegmentedControl'
pod 'SVProgressHUD'
pod 'iCarousel'
pod 'HPGrowingTextView'
pod 'JazzHands'
pod 'RCDraggableButton'
pod 'iVersion'
pod 'NJKWebViewProgress'
pod 'PSTCollectionView'
pod 'ZXingObjC'
pod 'Objective-LevelDB'

target :RCHadotTests, :exclusive => true do
    pod 'Kiwi/XCTest'
end
